title: The Gonzo Docs
description: Documentation for the GonzoFx plugin.
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Playable Demo: https://drive.google.com/file/d/1XUNRsBnmyhbPJMVDp0TVmzPreFm5C1Z6/view?usp=share_link
  Demo Project: https://github.com/MadTeaPartyGames/GonzoDemo

color_scheme: dark